modules:
  triage:
    system_info:
      fields:
        - os
        - kernel
        - hostname
        - timezone
        - interfaces
        - mounts
  system_info:
    fields:
      - os
      - kernel
      - hostname
      - timezone
      - interfaces
      - mounts
